baseURL: https://spencerfarley.com
languageCode: en-us
title: 5min Dev Essentials
theme: "github.com/adityatelange/hugo-PaperMod"

enableRobotsTXT: true
googleAnalytics: "G-YPSFPN3NJN"
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: true
    # noClasses: false
    style: monokai

outputFormats:
  RSS:
    baseName: "feed"

sitemap:
  changefreq: weekly
  filename: /sitemap/index.xml
  priority: 1.0

Params:
  # Paper theme settings
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  defaultTheme: light
  disableThemeToggle: true
  ShowPostNavLinks: true
  disableSpecial1stPost: true
  hideFooter: true
  footerSocialIcons:
    - name: RSS
      url: /feed.xml
  assets:
    disableHLJS: true

frontmatter:
  date: [ ":filename", ":default"] # https://github.com/gohugoio/hugo/pull/4494

permalinks: 
  posts: /:year/:month/:day/:slug

## Paper theme search
outputs:
  home:
    - HTML
    - RSS
    - JSON 

module:
  imports:
    - path: github.com/farlee2121/link-handling-mod-hugo-from-cache
    - path: github.com/danielfdickinson/image-handling-mod-hugo-dfd