baseURL: https://spencerfarley.com
languageCode: en-us
title: 5min Dev Essentials
theme: "github.com/adityatelange/hugo-PaperMod"


enableRobotsTXT: true
googleAnalytics: "G-YPSFPN3NJN"
rss: true
markup:
  goldmark:
    renderer:
      unsafe: true
Params:
  description: "Critical developer skills in 5 minutes or less."
  # Paper theme settings
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  defaultTheme: light
  disableThemeToggle: true

frontmatter:
  date: [ ":filename", ":default"] # https://github.com/gohugoio/hugo/pull/4494

permalinks: 
  posts: /:year/:month/:day/:slug

## Paper theme search
outputs:
  home:
    - HTML
    - RSS
    - JSON 

module:
  imports:
    - path: github.com/danielfdickinson/link-handling-mod-hugo-dfd
    - path: github.com/danielfdickinson/image-handling-mod-hugo-dfd