baseURL: https://spencerfarley.com
# disablePathToLower: true
languageCode: en-us
title: 5min Dev Essentials
theme: "github.com/adityatelange/hugo-PaperMod"

rss: true
Params:
  # Paper theme settings
  ShowReadingTime: true

