# https://docs.netlify.com/configure-builds/file-based-configuration


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """\
        default-src 'self'; \
        script-src 'self' cdn.jsdelivr.net cdnjs.cloudflare.com googletagmanager.com; \
        style-src 'self' fonts.googleapis.com cdn-images.mailchimp.com \
        image-src *;
        font-src 'self' fonts.googleapis.com;\
    """
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "none"
    
    