# https://docs.netlify.com/configure-builds/file-based-configuration


[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "v0.101.0"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """\
        default-src 'self'; \
        script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.jsdelivr.net cdnjs.cloudflare.com www.googletagmanager.com www.google-analytics.com; \
        style-src 'self' 'unsafe-inline' fonts.googleapis.com cdn-images.mailchimp.com; \
        img-src *; \
        font-src 'self' fonts.googleapis.com fonts.gstatic.com;\
        connect-src 'self' www.google-analytics.com;\
    """
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    # https://www.permissionspolicy.com/
    Permissions-Policy = """\
        accelerometer=(), \
        ambient-light-sensor=(), \
        autoplay=(), \
        battery=(), \
        camera=(), \
        cross-origin-isolated=(), \
        display-capture=(), \
        document-domain=(), \
        encrypted-media=(), \
        execution-while-not-rendered=(), \
        execution-while-out-of-viewport=(), \
        fullscreen=(), \
        geolocation=(), \
        gyroscope=(), \
        keyboard-map=(), \
        magnetometer=(), \
        microphone=(), \
        midi=(), \
        navigation-override=(), \
        payment=(), \
        picture-in-picture=(), \
        publickey-credentials-get=(), \
        screen-wake-lock=(), \
        sync-xhr=(), \
        usb=(), \
        web-share=(), \
        xr-spatial-tracking=()\
    """
    
    